[package]
name = "mev-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
revm = { workspace = true }
tokio = { workspace = true }
dotenv = { workspace = true }
eyre = { workspace = true }
mev_core = { workspace = true }
mev-analysis = { workspace = true }
clap = { workspace = true }
